export default [
'You are wonderful',
'Your hair is awesome',
'You can deadlift me',
'You pull me out of my comfort zone',
'I love kissing You',
'I met the most amazing person a year ago',
'Your smile warms my heart',
'I can lightly kiss your nose',
'I can rest my chin on your neck when we cuddle',
'You look great in a crop top',
'You got those booty gains',
'You love pedicures',
'You love back rubs',
'You are beautiful',
'You like to hike',
'You are an incredible singer',
'You have perfect pitch',
'You can rock climb',
'You can play piano',
'You\'re great at puzzles',
'You are super smart',
'You help people',
'You care about the world around you',
'You give people the benefit of the doubt',
'A tiny angel was born this week',
'You want to fix broken systems',
'You care about your friends',
'You love me',
'You love Sputnik',
'You care about your parents',
'You make me laugh',
'You ask me about my day',
'You made me sing on our first date',
'Your eyes make me smile',
'You make going out fun',
'You encourage us to eat at new places',
'You cook with me',
'You care about my family',
'You took care of me when I was sick',
'You work hard to keep our relationship healthy',
'You love to travel',
'You take care of me when I\'m feeling down',
'You make amazing risotto',
'An amazing person was born this week',
'You taught me to sip the tea',
'You encouraged me to get Sputnik',
'You still love me even though I\'m bad at washing dishes',
'You tell me I\'m cute',
'You dress great',
'Your Sputnik voice is adorable',
'You get me amazing presents',
'Test',
'I\'m ready for another year',
];